### ISSUE TITLE
processing comments

### ISSUE THREAD

**Issue by VinSpee** [outpunk/postcss-each#20]
Hi!

I'm writing a library that generates many classes. I'd like to use [mdcss](https://github.com/jonathantneal/mdcss) to document it, and i'd like to generate the docs. I'm using postcss-each to generate class names and values, and I'd like to also generate values in comments. Here's what I mean:

### input
```
@each $name, $size in (small, med, large), (.5rem, 1rem, 3rem) {
	/*---
		title: Font Size
		section: Typography
		---

		```html
		<span class=".font-$(name)">.font-$(name)</span>
		```
	*/
	.font-$(name),
	.font-$(name) {
		font-size: $(size);
	}
}
```

### output:
```
/*---
	title: Font Size
	section: Typography
	---

	```html
	<span class=".font-small">.font-small</span>
	```
*/
.font-small,
.font-small {
	font-size: .5rem;
}

/*---
	title: Font Size
	section: Typography
	---

	```html
	<span class=".font-med">.font-med</span>
	```
*/
.font-med,
.font-med {
	font-size: 1rem;
}

/*---
	title: Font Size
	section: Typography
	---

	```html
	<span class=".font-large">.font-large</span>
	```
*/
.font-large,
.font-large {
	font-size: 3rem;
}
```

It seems like we would just need to process the comment nodes in addition to other rules. Any interest in adding this feature? I tried on my own but couldn't figure out where the walking of those happens.

**Comment by outpunk** [comment]
Hi, I can add this feature, but I'm not sure if I have time for this for the nearest month :(

**Comment by VinSpee** [comment]
thank you! If I figure it out before then I will be sure to send you a PR

  

👋🏻

**Comment by outpunk** [comment]
Deal!

**Comment by VinSpee** [comment]
looks like the responsibility would exist in [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars) - I sent [a PR there](https://github.com/postcss/postcss-simple-vars/pull/49). Thanks - have a good one!
