### ISSUE TITLE
loop key:value map

### ISSUE THREAD

**Issue by ensk** [outpunk/postcss-each#26]
i 'm triying to loop a sass map like`  $main_palette: (main: "#0F1037", accent: "#BF642B"); `but i can't, if i do:

```
@each $key, $color in $main_palette {
	.color-$key {
		background-color: $color;	
	}
}
```
No variable is replaced
if i do.
```
@each $color in $main_palette {
	.color {
		background-color: $color;	
	}
}
```
the output is

```
.color {
    background-color: main: "#0F1037"
}

.color {
    background-color: accent: "#BF642B"
}
```

there is no plan for this feature?? is a bug ? or just i need to solve in other way..
thanks for help

**Comment by outpunk** [comment]
Just take a look at the [readme](https://github.com/outpunk/postcss-each). There is an example for this.

**Comment by Grawl** [comment]
@outpunk there is nothing similar in the readme. I want to do the same. How?

**Comment by Grawl** [comment]
Got an error with `postcss-simple-vars` https://github.com/outpunk/postcss-each/issues/14#issuecomment-261951230
