### ISSUE TITLE
Postcss v7 support?

### ISSUE THREAD

**Issue by asifshirazi** [outpunk/postcss-each#31]
Hi,

I've just update some of my project dependencies, and got following error.

`(rejection id: 3) Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.5, but postcss-each uses 6.0.23. Perhaps this is the source of the error below.`

Is there any plans to support PostCSS v7?

Thanks.

**Comment by outpunk** [comment]
I'm quite busy now with my kid and finishing my degree, so I almost have no time for my open source until the next year. So, if you want to make a PR, it's highly welcome =)
