### ISSUE TITLE
Example does not output correctly

### ISSUE THREAD

**Issue by marthakelly** [outpunk/postcss-each#9]
Hey there, I tried to run:

    $array: (foo, bar, baz);

    @each $val, $i in s, m, l  {
      .icon_size_$(val) {
        background: url('icons/$(array[$i]).png');
      }
    }

but the `$(array[$i])` is not being evaluated. Is there something I'm missing? I'm not certain if postcss-simple-vars supports that? Thanks!

**Comment by outpunk** [comment]
Hey!
My fault, I've forgotten to fix the docs. Yep, it's impossible – postcss-simple-vars works with plain values only. Updated the readme.

**Comment by outpunk** [comment]
@marthakelly Hey! Look at this https://github.com/outpunk/postcss-each/releases/tag/v0.6.0.
